pipeline {
    agent {label 'AGENT-1'}
    environment{
        PROJECT = 'expense'
        COMPONENT = 'backend'
        DEPLOY_TO = 'production'
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters {
        

        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')

        
    }

    stages {
        stage('Init and Plan') {
            steps {
                script{
                     withAWS(region: 'us-east-1', credentials: 'aws-devcreds'){
                        sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                        """


                     }
                    

                }
                   
                
            }
        }
        stage('Apply or Destroy'){
            input{
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-devcreds'){
                        sh """
                            cd 00-vpc
                            if [ ${params.ACTION} == 'apply' ]
                            then
                                terraform apply -auto-approve tfplan
                            elif [ ${params.ACTION} == 'destroy']
                            then
                                terraform destroy -auto-approve
                            fi
                        """
                    }
                }
                
            }
        }
        stage('Trigger SG'){
            when {
                expression { params.ACTION == 'apply'}
                
            }
            steps{
                build job: '10-sg', parameters: [string(name: 'ACTION' , value: 'apply')],
                propagate: true
            }
        }
    }   
    
        

    
    
    post {
        always {
            echo "this section runs always"

        }
        success {
            echo "this section run when pipeline success"
        }
        failure {
            echo "this section run when pipeline failure"
        }
    }
}

