pipeline {
    agent {label 'AGENT-1'}
    environment{
        PROJECT = 'expense'
        COMPONENT = 'backend'
        DEPLOY_TO = 'production'
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

    parameters {
         
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
     
       
     }

    stages {
        stage('init') {
            steps {
                script{
                     withAWS(region: 'us-east-1', credentials: 'aws-devcreds'){
                        sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan
                        """


                     }
                    

                }
                   
                
            }
        }
        stage('Apply'){
            input{
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-devcreds'){
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        
                        """
                    }
                }
                
            }
        }
        

        
    }   
}    
        
post {
        always {
            echo "this section runs always"

        }
        success {
            echo "this section run when pipeline success"
        }
        failure {
            echo "this section run when pipeline failure"
        }
    }


